[package]
name = "rust_scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
chrono = "0.4.41"
regex = "1.11.1"
reqwest = { version = "0.12.22", features = ["blocking"] }
scraper = "0.23.1"
url = "2.5.4"
