[package]
name = "rust_scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
chrono = "0.4.41"
regex = "1.11.1"
scraper = "0.23.1"
serde_json = "1.0.143"
ureq = { version = "3.1.2", features = ["cookies"] }
url = "2.5.4"
